In [1]:
from maze import Maze
import numpy as np
import argparse

In [2]:
a = Maze(verbose=False,step=1)
start=(10,0,0)
goal=(300,100,6)
if (a.solve_maze(start,goal)):
    path = a.back_track()    
    a.simple_plot_path()
    # a.game_plot()

--------------------------------------------------
		Initializing Maze
--------------------------------------------------
Start Node inside a Obstacle or out of bounds


In [4]:
abc = a.get_maze()

In [4]:
abc[500,0,0].get_is_visited()

True

In [23]:
ab = a.get_close_list()

In [24]:
ab[1]

[0.5 0. ] Angle-0

In [65]:
ab[9730].get_heuristic()

1.0

In [82]:
ab[973].get_parent()

(301, 1, 3)

In [76]:
abc[a.start_goal[-1]].get_position()

array([300,   0,   0], dtype=int32)

In [74]:
a.start_goal[-1]

(300, 0, 0)

In [3]:
path= a.back_track(a.new_goal.get_position())

No path from Start to goal


In [6]:
a.new_goal.get_cartisian()

array([299., 101.])

In [3]:
a.start_goal[-1]

(298, 601, 3)

In [8]:
print(abc[298,598,3])

Self: [299. 101.] Angle-90 Parent: (299, 598, 2) Cost: 599


In [10]:
abc[299,598,2].get_cartisian()

array([299. , 100.5])

In [11]:
abc[298,598,3].get_cartisian()

array([299., 101.])

In [3]:
len(path)

133